version: "3.5"
services:

  nginx:
    image: docker4ideas/ideas_nginx
    ports:
      - "8081:8081"

  ideas-studio-develop:
    image: docker4ideas/ideas-studio:develop
    #command: bash -c "tail -f /dev/null"
    command: bash -c "cd /ideas/studio && mvn spring-boot:run"
    ports:
      - "8080:8080"
    volumes: 
      - .:/ideas/studio
      - /tmp:/tmp # Necesario para el m√≥dulo de latex
  
#  ideas-latex-language:
#    image: docker4ideas/latex-module:develop
#    command: bash -c "tail -f /dev/null"
#    # command: bash -c "cd /ideas/latex-module && mvn spring-boot:run"
#    volumes:
#      - ../ideas-latex-module:/ideas/latex-module
#      - /tmp:/tmp


  #ideas-plaintext-language:
  #  image: docker4ideas/module:develop
  #  command: bash -c "tail -f /dev/null"
  #  # command: bash -c "cd /ideas/plaintext-module && mvn spring-boot:run"
  #  volumes:
  #    - ../ideas-plaintext-module:/ideas/plaintext-module

  #ideas-dockercompose-language:
  #  image: docker4ideas/module:develop
  #  command: bash -c "tail -f /dev/null"
  #  # command: bash -c "cd /ideas/dockercompose-module && mvn spring-boot:run"
  #  volumes:
  #    - ../ideas-dockercompose-module:/ideas/dockercompose-module


  ideas-dockerfile-language:
    image: docker4ideas/module-docker:develop
    command: bash -c "cd /usr/local/bin && wrapdocker && tail -f /dev/null"
    privileged: true
    # command: bash -c "cd /ideas/dockerfile-module && mvn spring-boot:run"
    volumes:
      - ../ideas-dockerfile-module:/ideas/dockerfile-module
